### ISSUE TITLE
MPS-rand-circ fails with type error

### ISSUE THREAD

**Issue by twobombs** [quicophy/mdopt#276]
### What happened?

whilst running MPS-rand-circ a type error pops up - preventing the notebook to continue 
https://github.com/quicophy/mdopt/blob/main/examples/random_circuit/mps-rand-circ.ipynb

![Screenshot from 2024-07-13 09-19-15](https://github.com/user-attachments/assets/060a6aca-900d-4670-9e6a-878706e5c7e8)

### What did you expect to happen?

a random circ test

### Anything else we need to know?

Python 3.10.12 on jupyter notebook 
![Screenshot from 2024-07-13 09-25-08](https://github.com/user-attachments/assets/0e2ce1ec-9929-4752-9d3e-80b25ccbfc8a)

### Environment

occurs both with pip3 install mdopt and from main installing it with -r requirements.txt

**Comment by meandmytram** [comment]
Hey @twobombs, thanks a lot for reporting this and very sorry for a late response, let me look into it and get back to you shortly!

**Comment by meandmytram** [comment]
@twobombs Can you try reproducing the error from the current version of the main branch please?

**Comment by twobombs** [comment]
I forgot to mention last time wich could be important:
after removing the random_circuit double declaration leaving only examples to import the notebook runs
![image](https://github.com/user-attachments/assets/d28c9fa6-9388-44b3-94f3-f81f9a281b17)
this time it stops at the same place with the same error 
![image](https://github.com/user-attachments/assets/55515d34-dda3-4f65-bf4b-8d1cff40127f)

**Comment by meandmytram** [comment]
Hey @twobombs, thanks for the clarification! 

First, the imports for the examples folder in a notebook usually require adding the directory to the `os.path`. Feel free to open PR, that should be just a one-liner: smth like `try import ...` and `except ModuleNotFoundError os.path[0].append(...)`.

Second, the current version of the function `mps.utils.create_simple_product_state` has an argument called `tolerance` which corresponds to how much we can deviate from "real" (normalised) quantum states. Thus the second error must go away once the main branch is pulled.

Thanks a bunch and let me know!
